export const SUBSCRIBER_LIST = 'SUBSCRIBER_LIST'
export const SUBSCRIBER_ADD = 'SUBSCRIBER_ADD'
export const SUBSCRIBER_UPDATE = 'SUBSCRIBER_UPDATE'
export const SUBSCRIBER_REMOVE = 'SUBSCRIBER_REMOVE'

export default {
  SUBSCRIBER_LIST,
  SUBSCRIBER_ADD,
  SUBSCRIBER_UPDATE,
  SUBSCRIBER_REMOVE,
}